name: Deploy Singolo Bucket S3

on:
  push:
    paths:
      - 's3-bucket/**' # Parte solo se modifichi qualcosa in questa cartella
  workflow_dispatch:  # Ti permette di avviarlo manualmente dalla scheda "Actions"

# Definiamo qui il nome del bucket a livello globale per tutto il workflow
env:
  TF_VAR_bucket_name: mio-demo-bucket-2026-per-terraform-progetto-demo

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: s3-bucket # Specifica la cartella di lavoro corretta

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
